# Generated by Django 4.1.6 on 2023-02-14 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('informe_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_colegio', models.CharField(max_length=255)),
                ('codigo_colegio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('rut', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('reportestr', models.CharField(max_length=20000)),
                ('decision', models.CharField(max_length=32)),
                ('comentario', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('id_informe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.informe')),
                ('rut_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.persona')),
            ],
        ),
    ]
