# Generated by Django 4.1.6 on 2023-02-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('reportestr', models.CharField(max_length=20000)),
            ],
        ),
    ]
