# Generated by Django 4.1.6 on 2023-02-14 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_report_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='informe',
            name='nombre_informe',
            field=models.CharField(default='test', max_length=255),
        ),
    ]
